### PR TITLE
fix .travis.yml

### PR DESCRIPTION
**Pull request by SamRoberts**
This makes the build work again, see http://commbank.artifactoryonline.com/commbank/ext-releases-local/au/com/cba/omnia/spectroscopy_2.11/0.1.0-SNAPSHOT-20180817022452-5a3a3bd-cdh-513-sam/

### CODE REVIEW

**Comment by SamRoberts** [comment]
all the other yaml I've done we've always increased indent, I was surprised to see it wasn't increased here. I can try moving it back down to an indentation level of 2 and see what happens

**Comment by rowandavies** [comment]
The `-` is treated as part of the indentation, so I would expect it to work either way.  The extra indentation is more typical, but we'll follow the existing style of @jameshales here.

**Comment by rowandavies** [comment]
Looks like the test build published.  Go ahead and merge after taking out this test release branch.

**Comment by rowandavies** [comment]
For the record:  it was a pretty subtle merge from master into the cdh-513 branch that led to the misalignment.  @cherianhormis  added the release branches line to the cdh-513 branch following the existing indentation, and separately @lancelet updated to ci2 with a different indentation to make it consistent with the rest of the file.  Then these two were merged here:

https://github.com/CommBank/spectroscopy/commit/2de2a7234ac58662511d8d850a54ac7fea00eabb

**Pull request merged**
